### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by Cascade1972** [TrentonBitterli/TrentonBitterli.github.io#1]
A little too much animation on the main page (specifically the bio), the color scheme is a bit too bright, the icon animations are a little too much and the colors on it don't look that well with the background color, on the 3D modeling page the bullet points are not next to the texts, the resume image could be changed to an iframe pdf

**Comment by TrentonBitterli** [comment]
Thanks for the feedback, I got rid of the animation on the bio tab and just increased the font. But I kept the animation for the text when you first load the page because I really like it and we are encouraged to use CSS Animations. I have been continuing to mess around with the color scheme and I will eventually settle on something more saturated. I changed the color on the Icons when you hover them and I made the animation a little less dramatic but I honestly saw this on another portfolio page by a professional web developer and I really liked the idea of the icon animation on hover. On the 3D modeling page, when you view it on mobile the bullet points are right next to the words so I have no clue why this is an issue on the desktop view. And finally as fart as the resume goes, I like it being the image because it shows off the resume at a legible size and then if you want to download the pdf you can always click my button I have provided underneath the image.
